### ISSUE TITLE
Give search engine bots access to pages (guest user)

### ISSUE THREAD

**Issue by coollog** [coollog/sublite#106]

**Comment by xtonyjiang** [comment]
I'll just make it so anyone can access the page, but if they're not logged in then an overlay asking to log in appears, similar to what Quora does. That way the bots should be able to still scrape our listings.

**Comment by coollog** [comment]
Hmm... removing an overlay would be very easy for anyone though. But that does sound like a viable idea. Also, we should have a page that shows a list of all of our listings in a bot-friendly format.

**Comment by xtonyjiang** [comment]
I could have an overlay + a check to see if you're logged in when you click the apply button. And I don't think most people would think of using inspect element :P

Yeah, the page would probably be a sitemap.xml.

**Comment by coollog** [comment]
Okay, then perhaps we can open the search to the public, and only require log in if they were to try to apply now or contact and owner.

We would just need to make sure to update $MStudent->me() to include default values for a guest, and wrap wherever $_SESSION vars are used with a function that also provides default values. I can set these up.

**Comment by coollog** [comment]
Alright I just made searching all public.
