### ISSUE TITLE
Housing Search Bugs

### ISSUE THREAD

**Issue by coollog** [coollog/sublite#108]
- [x] If you click on "from" field opens up a date box, and if you click a date to pick it, you are unable to make the date box come up for the "to" field.
- [x] "How many people" lets you pick negative numbers.
- [x] Search button is not visible on the page - this is important I think
- [x] if you search for new york in the main page, then just run search again once search results open, returns different results.

**Comment by xtonyjiang** [comment]
e33a3f2
