### ISSUE TITLE
If you open different links in new tabs in quick succession, they will all route to the same link

### ISSUE THREAD

**Issue by xtonyjiang** [coollog/sublite#232]
q pls help

**Comment by coollog** [comment]
Hmm is this a race condition? Most likely from what I can tell. You do need to be quite rapid to have this happen. Do you think this is too much of an issue?

**Comment by xtonyjiang** [comment]
well if i were a student searching for housing and jobs i would open tabs quite rapidly and be quite disillusioned

**Comment by coollog** [comment]
Fixed
