### ISSUE TITLE
Add list of predefined industries

### ISSUE THREAD

**Issue by coollog** [coollog/sublite#36]
- [x] add list of industries to company profile creation - @xtonyjiang 
- [x] add list of industries to search - @coollog
- [x] change all current listings' industries to ones on the list
- [x] add option to select multiple industries for a company profile

**Comment by xtonyjiang** [comment]
do we have a list yet?

**Comment by coollog** [comment]
I don't think we have a defined list right now. We wrote up something short last time but I think it's a bit too short. We should just look up a good decently-sized list.

**Comment by xtonyjiang** [comment]
Kk, did you see the OCS undergraduate career survey recently? There was a good list there.

**Comment by coollog** [comment]
Okay, yea this list looks good

Financial Services
Education
Consulting
Research (scientific/health/education, etc.)
Computer Science/Technology
Publishing/Media/Journalism
Healthcare
Fine or Performing Arts
Public Policy/Politics
Law/Legal Services
Communications/Marketing/Advertising/PR
Architecture/Design/Urban Planning
Consumer Goods/Retail
Entertainment/Professional Sports
Medical/Pharmaceutical
Environment

**Comment by coollog** [comment]
done
