### ISSUE TITLE
convert housing website

### ISSUE THREAD

**Issue by xtonyjiang** [coollog/sublite#66]
See Michelle's wireframes

Main:
- [x] listing creation and editing
- [x] listing search
- [x] listing view
- [x] student profile editing
- [x] student manage listings
- [x] student profile
- [x] map feature
- [x] comments
- [x] put in new team page and add housing faq back in

Misc.
- [x] normalize search price
- [x] search start should incorporate 50mi radius
- [x] calendar and slider for search
- [x] search results design
- [x] template message for contact owner
- [x] dynamic slider for listing photos
- [x] make 4 required photos
- [x] amenities not in search query
- [x] change shading for panels on viewsublet
- [x] left align anytime between
- [x] where did university go on viewsublet?
- [x] photo? messaging page?
- [x] remove white bar from top of message page

**Comment by coollog** [comment]
Note *: Make sure to have at least 4 photos be mandatory.

**Comment by coollog** [comment]
Finally finished everything on this huge checklist! :D
