### ISSUE TITLE
Have facebook tagline for recruiter side different

### ISSUE THREAD

**Issue by coollog** [coollog/sublite#67]
Have tagline instead be "Attract the New Generation Talent with your Company's Unique Personality." when on /jobs

**Comment by xtonyjiang** [comment]
What do you mean by tagline? Is it currently "SubLite – Your One-Stop Shop for a Great Summer!" right now?

**Comment by coollog** [comment]
Right now it's "Find summer internships and safe, student-only summer housing with SubLite! Verify your ".edu" email address to get started! It's completely free!"

**Comment by xtonyjiang** [comment]
fixed but need write/root access to server
